# CQ-03: Todo papel humano é subclasse (direta ou indireta) de Pessoa?
# (violação = um desses papéis sem caminho rdfs:subClassOf+ até esp:Pessoa)
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX esp: <https://w3id.org/ontologia-espirita/v1#>

SELECT ?papel
WHERE {
  VALUES ?papel {
    esp:Voluntario esp:Coordenador esp:Dirigente
    esp:PublicoAlvo esp:Frequentador esp:Assistido
  }
  FILTER NOT EXISTS { ?papel rdfs:subClassOf+ esp:Pessoa }
}
