# Quais casas são adesas, a que federativa, e por quais órgãos são atendidas?
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX esp: <https://w3id.org/ontologia-espirita/v1#>

SELECT ?casa ?modalidade ?status ?adesaA ?atendidaPor
WHERE {
  ?umaCasa a/rdfs:subClassOf* esp:Casa ;
           rdfs:label ?casa ;
           esp:adesaA ?federativa .
  ?federativa rdfs:label ?adesaA .
  OPTIONAL { ?umaCasa esp:statusAdesao ?status }
  OPTIONAL { ?umaCasa esp:modalidade ?modalidade }
  OPTIONAL {
    ?umaCasa esp:atendidaPor ?orgao .
    ?orgao rdfs:label ?atendidaPor .
  }
}
ORDER BY ?casa ?atendidaPor
